### ISSUE TITLE
Could you provide an example config or generate one, if none is existent?

### ISSUE THREAD

**Issue by KernelDev** [Centiq/CenSQL#1]
Hello,

I am looking for a config file. If none is present, even --help or /help does not work. 
Hope for a soon fix. That tool looks great!

Best regards,

KernelDev

**Comment by mikecentiq** [comment]
Hi. It's just a JSON file. So you could do:

```sh
mkdir ~/.censql
echo '{}' > ~/.censql/censql_settings
```

Then next time you run censql, even without any arguments, it will put some stuff inside there.

**Comment by KernelDev** [comment]
Wouldnt a initial creation be more useful? Just do the same in node
 fs.writeFile('~/.censql/censql_settings', '{}', function (err) {
        if (err) throw err;
        console.log('It\'s saved! in same location.');
    });

**Comment by mikecentiq** [comment]
FYI, I've just pushed up a fix for this and published to NPM. Thanks for reporting the issue.
