### ISSUE TITLE
Window title

### ISSUE THREAD

**Issue by KernelDev** [Centiq/CenSQL#2]
Hi,

I was using CenSql a bit and wondered if you could set the window title to the saved connection name when started with the --use flag. I am working with three different Hanas in three different windows. All are named CenSQL and I cant rename them with windows tools like title.

Kind regards,

KernelDev

**Comment by mikecentiq** [comment]
Good suggestion. Any idea how to do it? I just tried a few random libs from NPM and none of them worked in my testing.

**Comment by KernelDev** [comment]
/**
 * Sets the terminal title for your process.
 * @param  {String}  name          the name to set as your title
 * @return {Undefined}
 */
module.exports = function setTerminalTitle(name){
   process.stdout.write("\033]0;" + name + "\007");
};

found that one the interwebs(https://github.com/bioball/set-terminal-title/blob/master/index.js). Works fine on my setting. I love magic escape sequence stuff

**Comment by mikecentiq** [comment]
I didn't realise that we were already setting the title. I've updated it to add the connection name to the title when --use is used. Published to npm a few seconds ago.
